### ISSUE TITLE
What is this AQI Card?

### ISSUE THREAD

**Issue by spencerthayer** [AmoebeLabs/ha-m3-themes#1]
<img width="588" alt="Screen Shot 2022-02-22 at 11 04 26 AM" src="https://user-images.githubusercontent.com/1019815/155201155-5de68653-34cf-437a-ab79-900175b73395.png">

This AQI card is very cool. Do you have a code example of how one can get this result with HAM3?

**Comment by AmoebeLabs** [comment]
Thanks!

The AQI card is created with the Swiss Army Knife (SAK) custom card. Styling is done using HAM3. So you can't create this card with HAM3. You need SAK for this, but that card is not yet released!

At this moment I can't tell when it will be released.

**Comment by spencerthayer** [comment]
Is [Swiss Army Knife](https://github.com/AmoebeLabs/swiss-army-knife) installable via HACS?

**Comment by AmoebeLabs** [comment]
Yes, once released it will be available via HACS.

You linked the documentation repository, which you can view at https://swiss-army-knife.docs.amoebelabs.com/.

under the examples section, you will find example 12 with the AQI card in it.

**Comment by spencerthayer** [comment]
Thank you. I cannot wait until SAK is released. Is there a newsletter or something that I can sign up to? Or should I just watch all activity in GitHub?

**Comment by AmoebeLabs** [comment]
> Thank you. I cannot wait until SAK is released. Is there a newsletter or something that I can sign up to? Or should I just watch all activity in GitHub?

There is an issue in the SAK documentation repository, https://github.com/AmoebeLabs/swiss-army-knife/issues/1 about the public release: If that issue is closed, SAK is released 🥳 

Furthermore, I intend to post it on the HA community forum too!

And last but not least: It will appear in HACS.

**Comment by AmoebeLabs** [comment]
The Swiss Army Knife card has been released on June 19th, 2022.

It is also merged into HACS on that date, so should be/become available in the store.

The manual has moved and is published on: https://swiss-army-knife-card-manual.amoebelabs.com/
